version: '3'
services:
  echo-mysql-local:
    image: mysql:5.7
    container_name: echo-mysql-local
    ports:
      - 4444:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/echo_db_create.sql:/docker-entrypoint-initdb.d/echo_db_create.sql
    environment:
      MYSQL_ROOT_PASSWORD: "echo"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  echo-meta-server:
    image: docker.io/library/meta-server
    container_name: echo-meta-server
    ports:
      - 4826:8080
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: echo
      SPRING_DATASOURCE_URL: jdbc:mysql://echo-mysql-local:3306/echo?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&autoConnect=true
    depends_on: 
      - echo-mysql-local
  echo-fe-ui:
    image: registry.cn-beijing.aliyuncs.com/virjar/echo-fe-ui:20210430
    container_name: echo-fe-ui
    ports:
      - 8999:80
    volumes:
      - ./echo-fe-nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      API_ENTRY: http://echo-meta-server:8080
    depends_on: 
      - echo-meta-server
  # echo-nat-server:
  #   image: registry.cn-beijing.aliyuncs.com/virjar/echo-nat-server:latest
  #   container_name: echo-nat-server
  #   ports:
  #     - 12000-12010:12000-12010
  #     - 5699:5699
  #     - 5698:5698
  #   environment:
  #     API_ENTRY: http://echo-meta-server:8080
  #     SERVER_ID: echo-nat-server-001
  #     MAPPING_SPACE: 12000-12010
  #   depends_on: 
  #     - echo-meta-server
  echo-http-proxy-server:
    image: registry.cn-beijing.aliyuncs.com/virjar/echo-http-proxy-server:20210510
    container_name: echo-http-proxy-server
    ports:
      - 13000-13020:13000-13020
      - 5710:5710
    environment:
      API_ENTRY: http://echo-meta-server:8080/
      MAPPING_SERVER_URL: http://echo-meta-server:8080/echoNatApi/connectionList
      AUTH_CONFIG_URL: http://echo-meta-server:8080/echoNatApi/syncAuthConfig
      SERVER_ID: echo-http-proxy-001
      MAPPING_SPACE: 13000-13020
    depends_on: 
      - echo-meta-server
  # echo-client:
  #   image: registry.cn-beijing.aliyuncs.com/virjar/echo-client:latest
  #   container_name: echo-client
  #   environment:
  #     API_ENTRY: http://echo-meta-server:8080/
  #     ECHO_ACCOUNT: admin
  #     ECHO_PASSWORD: admin
  #   depends_on: 
  #     - echo-meta-server
  #     - echo-http-proxy-server